/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/identity/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea o vincula una identidad */
        post: operations["identityResolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista usuarios con filtros opcionales */
        get: operations["identityListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un usuario con identidades */
        get: operations["identityGetUser"];
        put?: never;
        post?: never;
        /** Soft-delete de usuario */
        delete: operations["identityDeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fusiona dos usuarios */
        post: operations["identityMerge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte agregado de identidades */
        get: operations["identityReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/users/{userId}/ai-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activa/desactiva IA para un usuario */
        patch: operations["identityAISettings"];
        trace?: never;
    };
    "/v1/messages/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envía un mensaje a un canal */
        post: operations["messagesSend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de un mensaje específico */
        get: operations["messagesGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/instagram/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista conversaciones activas de Instagram */
        get: operations["instagramConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/instagram/{igsid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envía DM a un IGSID específico */
        post: operations["instagramSendDM"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista paginada de conversaciones */
        get: operations["conversationsList"];
        put?: never;
        /** Crear una conversación manualmente */
        post: operations["conversationsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una conversación */
        get: operations["conversationsGet"];
        put?: never;
        post?: never;
        /** Archiva una conversación (soft-delete) */
        delete: operations["conversationsDelete"];
        options?: never;
        head?: never;
        /** Actualizar configuración de conversación */
        patch: operations["conversationsUpdate"];
        trace?: never;
    };
    "/v1/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mensajes de una conversación */
        get: operations["conversationsMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scraping/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar tareas de scraping */
        get: operations["scrapingList"];
        put?: never;
        /** Crear tarea de scraping */
        post: operations["scrapingCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scraping/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver una tarea de scraping */
        get: operations["scrapingGet"];
        put?: never;
        post?: never;
        /** Borrar tarea de scraping */
        delete: operations["scrapingDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scraping/cleanup-expired": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cleanup manual de tareas expiradas */
        post: operations["scrapingCleanupExpired"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista emails enviados */
        get: operations["emailList"];
        put?: never;
        /** Envía un email */
        post: operations["emailSend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/emails/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un email */
        get: operations["emailGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas las tareas programadas */
        get: operations["schedulerList"];
        put?: never;
        /** Crear tarea programada */
        post: operations["schedulerCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una tarea programada */
        get: operations["schedulerGet"];
        put?: never;
        post?: never;
        /** Borrar tarea programada */
        delete: operations["schedulerDelete"];
        options?: never;
        head?: never;
        /** Actualizar tarea programada */
        patch: operations["schedulerUpdate"];
        trace?: never;
    };
    "/v1/schedules/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial de ejecuciones */
        get: operations["schedulerRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedules/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pausar una tarea */
        post: operations["schedulerPause"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedules/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivar tarea pausada */
        post: operations["schedulerResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedules/{id}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disparar tarea ahora */
        post: operations["schedulerTrigger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envía un mensaje al agente IA */
        post: operations["agentChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista conversaciones del agente */
        get: operations["agentConversationsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle + historial de conversación */
        get: operations["agentConversationsGet"];
        put?: never;
        post?: never;
        /** Borra una conversación */
        delete: operations["agentConversationsDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista memorias del usuario */
        get: operations["agentMemoriesList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/memories/{userId}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Borra una memoria específica */
        delete: operations["agentMemoriesDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conexión SSE para eventos en tiempo real
         * @description Stream Server-Sent Events. Una sola conexión cubre todos los servicios.
         *     Los topics se separan por coma.
         */
        get: operations["eventsSubscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            statusCode: number;
            /** Format: date-time */
            timestamp: string;
            path: string;
            message: string;
        };
        AcceptedResponse: {
            success?: boolean;
            message?: string;
        };
        IdentityResolveRequest: {
            channel: string;
            channelUserId: string;
            displayName?: string;
            phone?: string;
            /** Format: email */
            email?: string;
            username?: string;
            /** Format: uri */
            avatarUrl?: string;
            trustScore?: number;
            metadata?: Record<string, never>;
        };
        Identity: {
            channel: string;
            channelUserId: string;
            displayName?: string;
            trustScore?: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            aiEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
            identities: components["schemas"]["Identity"][];
        };
        UserDetail: {
            user: components["schemas"]["User"];
            identities: components["schemas"]["Identity"][];
            contacts: Record<string, never>[];
            nameHistory: Record<string, never>[];
        };
        IdentityMergeRequest: {
            /** Format: uuid */
            primaryUserId: string;
            /** Format: uuid */
            secondaryUserId: string;
            reason: string;
        };
        IdentityReport: {
            totalUsers: number;
            usersByChannel: {
                [key: string]: number;
            };
            deletedUsers: number;
            averageIdentitiesPerUser: number;
        };
        SendMessageRequest: {
            /** @enum {string} */
            channel: "whatsapp" | "instagram" | "slack" | "notion" | "tiktok" | "facebook";
            recipients: string[];
            message: string;
            operation?: string;
            /** Format: uri */
            mediaUrl?: string;
            metadata?: Record<string, never>;
        };
        SendMessageResponse: {
            /** Format: uuid */
            id: string;
            accepted: boolean;
            channel: string;
            recipients: string[];
            message: string;
            /** @enum {string} */
            status: "PENDING";
            /** Format: date-time */
            createdAt: string;
        };
        MessageStatus: {
            /** Format: uuid */
            id: string;
            channel: string;
            recipients: string[];
            message: string;
            /** @enum {string} */
            status: "PENDING" | "SENT" | "FAILED" | "PARTIAL";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        InstagramConversation: {
            conversationId: string;
            igsid: string;
            username: string;
        };
        InstagramSendResponse: {
            /** Format: uuid */
            messageId: string;
            igsid: string;
            /** @enum {string} */
            status: "SENT";
            /** Format: date-time */
            timestamp: string;
        };
        /** @enum {string} */
        ConvStatus: "ACTIVE" | "WAITING_AGENT" | "WITH_AGENT" | "ARCHIVED" | "CLOSED" | "OPEN" | "WAITING";
        Conversation: {
            /** Format: uuid */
            id: string;
            channel: string;
            channelUserId: string;
            /** Format: uuid */
            userId?: string | null;
            topic?: string | null;
            aiEnabled: boolean;
            agentAssigned?: string | null;
            status: components["schemas"]["ConvStatus"];
            messageCount: number;
            /** Format: date-time */
            lastMessageAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ConversationListResponse: {
            data: components["schemas"]["Conversation"][];
            total: number;
            limit: number;
            offset: number;
        };
        CreateConversationRequest: {
            channel: string;
            channelUserId?: string;
            topic?: string;
            aiEnabled?: boolean;
        };
        UpdateConversationRequest: {
            aiEnabled?: boolean;
            agentAssigned?: string;
            status?: components["schemas"]["ConvStatus"];
        };
        ConversationMessage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** @enum {string} */
            direction?: "INBOUND" | "OUTBOUND";
            /** @enum {string} */
            sender?: "USER" | "BOT" | "AGENT" | "SYSTEM";
            content: string;
            from?: string;
            aiGenerated?: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ScrapingSelector: {
            [key: string]: string | {
                css?: string;
                attr?: string;
                xpath?: string;
                text?: string;
            };
        };
        ScrapingLogin: {
            usernameSelector?: string;
            passwordSelector?: string;
            submitSelector?: string;
            username?: string;
            password?: string;
            sessionKey?: string;
            successSelector?: string;
        };
        ScrapingFlowStep: {
            /** @enum {string} */
            type?: "navigate" | "click" | "type" | "wait" | "scroll" | "extract";
            url?: string;
            selector?: string;
            text?: string;
            delayMs?: number;
            timeoutMs?: number;
            toBottom?: boolean;
            px?: number;
            sleepMs?: number;
            selectors?: components["schemas"]["ScrapingSelector"];
        };
        CreateScrapingTaskRequest: {
            /** Format: uri */
            url: string;
            userId?: string;
            /** @enum {string} */
            strategy: "auto" | "extract" | "search" | "login_then_extract" | "login_then_search" | "custom_flow";
            selectors?: components["schemas"]["ScrapingSelector"];
            login?: components["schemas"]["ScrapingLogin"];
            flow?: components["schemas"]["ScrapingFlowStep"][];
            search?: {
                input?: string;
                submit?: string;
                query?: string;
            };
            output?: {
                targets?: string[];
                notion?: Record<string, never>;
                whatsapp?: {
                    to?: string;
                };
                email?: {
                    to?: string[];
                    subject?: string;
                };
            };
            performance?: {
                blockResources?: boolean;
                cacheTtlMs?: number;
                timeoutMs?: number;
            };
            lifecycle?: {
                expiresAfterMs?: number;
                metadata?: Record<string, never>;
            };
        };
        ScrapingTaskCreatedResponse: {
            /** Format: uuid */
            jobId: string;
            accepted: boolean;
            subscribeTo: string;
        };
        ScrapingTask: {
            /** Format: uuid */
            id: string;
            userId?: string;
            /** Format: uri */
            url: string;
            strategy: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCESS" | "FAILED";
            result?: Record<string, never> | null;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            durationMs?: number | null;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        SendEmailRequest: {
            to: string[];
            cc?: string[];
            bcc?: string[];
            from?: string;
            /** Format: email */
            replyTo?: string;
            subject: string;
            html?: string;
            text?: string;
            idempotencyKey?: string;
            metadata?: Record<string, never>;
        };
        EmailMessage: {
            /** Format: uuid */
            id: string;
            to: string[];
            from?: string;
            subject: string;
            provider?: string;
            providerMessageId?: string;
            /** @enum {string} */
            status: "QUEUED" | "SENT" | "DELIVERED" | "BOUNCED" | "COMPLAINED" | "FAILED" | "OPENED" | "CLICKED";
            /** Format: date-time */
            sentAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        EmailEvent: {
            /** Format: uuid */
            id: string;
            type: string;
            /** Format: date-time */
            occurredAt: string;
            rawPayload?: Record<string, never>;
        };
        EmailMessageDetail: components["schemas"]["EmailMessage"] & {
            /** Format: date-time */
            deliveredAt?: string | null;
            /** Format: date-time */
            openedAt?: string | null;
            events?: components["schemas"]["EmailEvent"][];
        };
        CreateScheduleRequest: {
            name: string;
            description?: string;
            /** @enum {string} */
            scheduleType: "CRON" | "INTERVAL" | "ONCE";
            cronExpression?: string;
            intervalMs?: number;
            /** Format: date-time */
            runAt?: string;
            /** @default America/Bogota */
            timezone: string;
            targetRoutingKey: string;
            payload: Record<string, never>;
            maxRetries?: number;
            retryBackoffMs?: number;
            /** @default 300000 */
            maxLatenessMs: number;
            createdBy?: string;
        };
        UpdateScheduleRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            scheduleType?: "CRON" | "INTERVAL" | "ONCE";
            cronExpression?: string;
            intervalMs?: number;
            /** Format: date-time */
            runAt?: string;
            timezone?: string;
            targetRoutingKey?: string;
            payload?: Record<string, never>;
            maxRetries?: number;
            retryBackoffMs?: number;
            maxLatenessMs?: number;
            createdBy?: string;
        };
        ScheduledTask: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            /** @enum {string} */
            scheduleType: "CRON" | "INTERVAL" | "ONCE";
            cronExpression?: string | null;
            intervalMs?: number | null;
            /** Format: date-time */
            runAt?: string | null;
            timezone?: string;
            targetRoutingKey: string;
            payload: Record<string, never>;
            /** @enum {string} */
            status: "ACTIVE" | "PAUSED" | "COMPLETED" | "FAILED";
            /** Format: date-time */
            nextFireAt?: string | null;
            fireCount: number;
            failureCount: number;
            /** Format: date-time */
            lastFiredAt?: string | null;
            lastStatus?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TaskExecution: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: string;
            /** Format: date-time */
            scheduledFor: string;
            /** Format: date-time */
            firedAt: string;
            latencyMs?: number;
            /** @enum {string} */
            status: "SUCCESS" | "FAILED" | "SKIPPED_LATE";
            publishedTo: string;
            idempotencyKey: string;
            error?: string | null;
        };
        AgentChatRequest: {
            message: string;
            /** Format: uuid */
            conversationId?: string;
            userId?: string;
            enableStreaming?: boolean;
        };
        AgentToolUse: {
            name: string;
            input: Record<string, never>;
            output: Record<string, never>;
            error?: string;
        };
        AgentChatResponse: {
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            messageId: string;
            finalText: string;
            toolsUsed?: components["schemas"]["AgentToolUse"][];
            model?: string;
            usage?: {
                inputTokens?: number;
                outputTokens?: number;
            };
            /** Format: date-time */
            createdAt: string;
        };
        AgentConversation: {
            /** Format: uuid */
            id: string;
            userId?: string;
            title: string;
            /** Format: date-time */
            lastMessageAt: string;
            messageCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        AgentMessage: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
            toolUses?: components["schemas"]["AgentToolUse"][];
            /** Format: date-time */
            createdAt: string;
        };
        AgentConversationDetail: {
            /** Format: uuid */
            id: string;
            userId?: string;
            title: string;
            messages: components["schemas"]["AgentMessage"][];
            /** Format: date-time */
            createdAt: string;
        };
        AgentMemory: {
            key: string;
            value: string;
            type: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Error de validación (400) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso no encontrado (404) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    identityResolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityResolveRequest"];
            };
        };
        responses: {
            /** @description Identity resolution queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
        };
    };
    identityListUsers: {
        parameters: {
            query?: {
                channel?: string;
                includeDeleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de usuarios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    identityGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuario con identidades */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    identityDeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-delete queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
        };
    };
    identityMerge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityMergeRequest"];
            };
        };
        responses: {
            /** @description Merge queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
        };
    };
    identityReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reporte agregado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityReport"];
                };
            };
        };
    };
    identityAISettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    aiEnabled: boolean;
                };
            };
        };
        responses: {
            /** @description AI settings update queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
        };
    };
    messagesSend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Mensaje encolado */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    messagesGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado del mensaje */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageStatus"];
                };
            };
        };
    };
    instagramConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de conversaciones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstagramConversation"][];
                };
            };
        };
    };
    instagramSendDM: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                igsid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    message: string;
                    /** Format: uri */
                    mediaUrl?: string;
                };
            };
        };
        responses: {
            /** @description DM enviado */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstagramSendResponse"];
                };
            };
        };
    };
    conversationsList: {
        parameters: {
            query?: {
                channel?: string;
                status?: components["schemas"]["ConvStatus"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
        };
    };
    conversationsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Conversación creada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    conversationsGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle de conversación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    conversationsDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo exitoso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
        };
    };
    conversationsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversationRequest"];
            };
        };
        responses: {
            /** @description Conversación actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    conversationsMessages: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de mensajes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMessage"][];
                };
            };
        };
    };
    scrapingList: {
        parameters: {
            query?: {
                limit?: number;
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de tareas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapingTask"][];
                };
            };
        };
    };
    scrapingCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScrapingTaskRequest"];
            };
        };
        responses: {
            /** @description Tarea creada */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapingTaskCreatedResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    scrapingGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle de la tarea */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapingTask"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    scrapingDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["schemas"]["AcceptedResponse"];
        };
    };
    scrapingCleanupExpired: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado del cleanup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted?: number;
                    };
                };
            };
        };
    };
    emailList: {
        parameters: {
            query?: {
                limit?: number;
                direction?: "inbound" | "outbound";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de emails */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailMessage"][];
                };
            };
        };
    };
    emailSend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailRequest"];
            };
        };
        responses: {
            /** @description Email enviado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailMessage"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    emailGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email con historial de eventos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailMessageDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    schedulerList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de tareas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTask"][];
                };
            };
        };
    };
    schedulerCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleRequest"];
            };
        };
        responses: {
            /** @description Tarea creada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTask"];
                };
            };
        };
    };
    schedulerGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle de la tarea */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTask"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    schedulerDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["schemas"]["AcceptedResponse"];
        };
    };
    schedulerUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleRequest"];
            };
        };
        responses: {
            /** @description Tarea actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTask"];
                };
            };
        };
    };
    schedulerRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historial de ejecuciones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskExecution"][];
                };
            };
        };
    };
    schedulerPause: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tarea pausada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTask"];
                };
            };
        };
    };
    schedulerResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tarea reactivada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTask"];
                };
            };
        };
    };
    schedulerTrigger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trigger aceptado */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                    };
                };
            };
        };
    };
    agentChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentChatRequest"];
            };
        };
        responses: {
            /** @description Respuesta del agente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentChatResponse"];
                };
            };
        };
    };
    agentConversationsList: {
        parameters: {
            query: {
                userId: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de conversaciones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConversation"][];
                };
            };
        };
    };
    agentConversationsGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversación con mensajes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConversationDetail"];
                };
            };
        };
    };
    agentConversationsDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversación borrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agentMemoriesList: {
        parameters: {
            query: {
                userId: string;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de memorias */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMemory"][];
                };
            };
        };
    };
    agentMemoriesDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memoria borrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eventsSubscribe: {
        parameters: {
            query: {
                topics: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream (text/event-stream) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
